version: '3.7'
services:
  mysql:
    image: mysql:8.3.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      # Uncomment the following line if you want to persist MySQL data on your host machine
      # - ~/volumes/jhipster/twitterClone/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=twitterclone
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-p$password']
      interval: 10s
      timeout: 5s
      retries: 5
