package com.strahov.twitterclone.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HashTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagAllPropertiesEquals(HashTag expected, HashTag actual) {
        assertHashTagAutoGeneratedPropertiesEquals(expected, actual);
        assertHashTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagAllUpdatablePropertiesEquals(HashTag expected, HashTag actual) {
        assertHashTagUpdatableFieldsEquals(expected, actual);
        assertHashTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagAutoGeneratedPropertiesEquals(HashTag expected, HashTag actual) {
        assertThat(expected)
            .as("Verify HashTag auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagUpdatableFieldsEquals(HashTag expected, HashTag actual) {
        assertThat(expected)
            .as("Verify HashTag relevant properties")
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagUpdatableRelationshipsEquals(HashTag expected, HashTag actual) {
        assertThat(expected)
            .as("Verify HashTag relationships")
            .satisfies(e -> assertThat(e.getTweets()).as("check tweets").isEqualTo(actual.getTweets()))
            .satisfies(e -> assertThat(e.getMentions()).as("check mentions").isEqualTo(actual.getMentions()));
    }
}
